name: Deploy to Azure ACI

on:
  workflow_run:
    workflows: ['Build and Test']
    types: [completed]
    branches:
      - main

env:
  ACI_LOCATION: westus                                      # set this to your preferred ACI region, e.g. west us
  ACI_NAME: aci-github-actions-example-nodejs               # set this to your ACI name
  ACI_REPOSITORY: github-actions-example-nodejs-repository  # set this to your ACI repository name

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$ACI_REPOSITORY:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$ACI_REPOSITORY:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/$ACI_REPOSITORY:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: $ACI_NAME
          location: $ACI_LOCATION